# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            iXport iPhone SMS
tagline:          'A tool for exporting SMS conversation'
description:      ''
url:              http://ale46.github.io/iXport-iPhone-SMS/
baseurl:          http://ale46.github.io/iXport-iPhone-SMS/
author:
  name:           'Ale46'
  url:            https://ale46.github.io/iXport-iPhone-SMS/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Ale46/iXport-iPhone-SMS
  main: 		  https://ale46.github.io/

download:
  windows:        ''
  mac:            ''
  linux:          ''
  all: 		      https://github.com/downloads/Ale46/iXport-iPhone-SMS/iXport_iPhone_SMS-all.zip

exclude: Rakefile
